// flow-typed signature: 1f59dfae801988f93067bd9b3af2f3b9
// flow-typed version: <<STUB>>/event-stream_v^3.3.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'event-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'event-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'event-stream/examples/pretty' {
  declare module.exports: any;
}

declare module 'event-stream/test/connect.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/helper/index' {
  declare module.exports: any;
}

declare module 'event-stream/test/merge.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/parse.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/pause.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/pipeline.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/readable.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/readArray.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/replace.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/simple-map.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/spec.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/split.asynct' {
  declare module.exports: any;
}

declare module 'event-stream/test/stringify' {
  declare module.exports: any;
}

declare module 'event-stream/test/writeArray.asynct' {
  declare module.exports: any;
}

// Filename aliases
declare module 'event-stream/examples/pretty.js' {
  declare module.exports: $Exports<'event-stream/examples/pretty'>;
}
declare module 'event-stream/index' {
  declare module.exports: $Exports<'event-stream'>;
}
declare module 'event-stream/index.js' {
  declare module.exports: $Exports<'event-stream'>;
}
declare module 'event-stream/test/connect.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/connect.asynct'>;
}
declare module 'event-stream/test/helper/index.js' {
  declare module.exports: $Exports<'event-stream/test/helper/index'>;
}
declare module 'event-stream/test/merge.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/merge.asynct'>;
}
declare module 'event-stream/test/parse.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/parse.asynct'>;
}
declare module 'event-stream/test/pause.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/pause.asynct'>;
}
declare module 'event-stream/test/pipeline.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/pipeline.asynct'>;
}
declare module 'event-stream/test/readable.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/readable.asynct'>;
}
declare module 'event-stream/test/readArray.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/readArray.asynct'>;
}
declare module 'event-stream/test/replace.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/replace.asynct'>;
}
declare module 'event-stream/test/simple-map.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/simple-map.asynct'>;
}
declare module 'event-stream/test/spec.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/spec.asynct'>;
}
declare module 'event-stream/test/split.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/split.asynct'>;
}
declare module 'event-stream/test/stringify.js' {
  declare module.exports: $Exports<'event-stream/test/stringify'>;
}
declare module 'event-stream/test/writeArray.asynct.js' {
  declare module.exports: $Exports<'event-stream/test/writeArray.asynct'>;
}
