// flow-typed signature: 1b048478d942523945260e6c2bf79f6b
// flow-typed version: <<STUB>>/schema.org_v^3.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'schema.org'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'schema.org' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'schema.org/context' {
  declare module.exports: any;
}

declare module 'schema.org/data/index' {
  declare module.exports: any;
}

declare module 'schema.org/test/test' {
  declare module.exports: any;
}

declare module 'schema.org/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'schema.org/context.js' {
  declare module.exports: $Exports<'schema.org/context'>;
}
declare module 'schema.org/data/index.js' {
  declare module.exports: $Exports<'schema.org/data/index'>;
}
declare module 'schema.org/index' {
  declare module.exports: $Exports<'schema.org'>;
}
declare module 'schema.org/index.js' {
  declare module.exports: $Exports<'schema.org'>;
}
declare module 'schema.org/test/test.js' {
  declare module.exports: $Exports<'schema.org/test/test'>;
}
declare module 'schema.org/utils.js' {
  declare module.exports: $Exports<'schema.org/utils'>;
}
