// flow-typed signature: 76d7ca2b4f1fc4e7d72b320d28f404bb
// flow-typed version: <<STUB>>/url-template_v^2.0.8/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-template' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-template/lib/url-template' {
  declare module.exports: any;
}

declare module 'url-template/test/uritemplate-test' {
  declare module.exports: any;
}

declare module 'url-template/test/url-template-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-template/lib/url-template.js' {
  declare module.exports: $Exports<'url-template/lib/url-template'>;
}
declare module 'url-template/test/uritemplate-test.js' {
  declare module.exports: $Exports<'url-template/test/uritemplate-test'>;
}
declare module 'url-template/test/url-template-test.js' {
  declare module.exports: $Exports<'url-template/test/url-template-test'>;
}
