// flow-typed signature: 0822170f53b13c6b55aec43f7029ba4c
// flow-typed version: <<STUB>>/@zillow/schema.org_v^2.6.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@zillow/schema.org'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@zillow/schema.org' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@zillow/schema.org/context' {
  declare module.exports: any;
}

declare module '@zillow/schema.org/data/index' {
  declare module.exports: any;
}

declare module '@zillow/schema.org/test/test' {
  declare module.exports: any;
}

declare module '@zillow/schema.org/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@zillow/schema.org/context.js' {
  declare module.exports: $Exports<'@zillow/schema.org/context'>;
}
declare module '@zillow/schema.org/data/index.js' {
  declare module.exports: $Exports<'@zillow/schema.org/data/index'>;
}
declare module '@zillow/schema.org/index' {
  declare module.exports: $Exports<'@zillow/schema.org'>;
}
declare module '@zillow/schema.org/index.js' {
  declare module.exports: $Exports<'@zillow/schema.org'>;
}
declare module '@zillow/schema.org/test/test.js' {
  declare module.exports: $Exports<'@zillow/schema.org/test/test'>;
}
declare module '@zillow/schema.org/utils.js' {
  declare module.exports: $Exports<'@zillow/schema.org/utils'>;
}
